FROM httpd:2.4-bookworm

# Install required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy dispatcher module and configurations
COPY modules/dispatcher*.so /usr/local/apache2/modules/mod_dispatcher.so
COPY conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY conf/dispatcher.any /usr/local/apache2/conf/dispatcher.any

# Create cache directory and grant write permissions to Apache daemon
RUN mkdir -p /usr/local/apache2/htdocs/cache && \
    chown -R daemon:daemon /usr/local/apache2/htdocs/cache

EXPOSE 80