# Load AEM Dispatcher Module
LoadModule dispatcher_module modules/mod_dispatcher.so

<IfModule dispatcher_module>
  DispatcherConfig conf/dispatcher.any
  DispatcherLog    logs/dispatcher.log
  DispatcherLogLevel debug
  DispatcherNoServerHeader 0
  DispatcherDeclineRoot 0
  DispatcherUseProcessedURL 0
</IfModule>

# Force Apache to pass all incoming requests through mod_dispatcher
# <Location />
#   <IfModule dispatcher_module>
#     SetHandler dispatcher-handler
#   </IfModule>
# </Location>

# Set cache docroot directory
DocumentRoot "/usr/local/apache2/htdocs/cache"

<Directory "/usr/local/apache2/htdocs/cache">
  Options FollowSymLinks
  AllowOverride None
  Require all granted

    <IfModule dispatcher_module>
      SetHandler dispatcher-handler
      ModMimeUsePathInfo On
    </IfModule>
</Directory>